services:
  webapi:
    build: .
    ports:
      - "8072:8072"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Quiz;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Your_password123 
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"